---
- name: Install EPEL (CentOS)
  yum:
    name: epel-release
    state: present
    update_cache: yes

- name: Install packages (CentOS)
  yum:
    name: python34,uwsgi,uwsgi-plugin-python3,uwsgi-logger-file,nginx,git,wget
    state: present
    update_cache: yes
