---
- name: Replace global nginx config with clean (hostless) default
  copy:
    src: '{{ item }}'
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - 'files/nginx_hostless_{{ ansible_distribution }}.conf'
  when: nginx_hostless_global_config

- name: Create nginx config
  template:
    src: templates/nginx-host.conf.j2
    dest: '{{ nginx_dir }}/{{ app_name }}.conf'
    owner: root
    group: root
    mode: 0644

- name: Create uWSGI config
  template:
    src: templates/uwsgi-vassal.ini.j2
    dest: '{{ uwsgi_dir }}/{{ app_name }}.ini'
    owner: root
    group: root
    mode: 0644
