---
- name: Install EPEL (EL)
  yum:
    name: epel-release
    state: present
    update_cache: yes

- name: Install packages (CentOS 7)
  when: ansible_distribution_major_version == "7"
  yum:
    name: python36,uwsgi,uwsgi-plugin-python36,uwsgi-logger-file,nginx,git,wget
    state: present
    update_cache: yes

- name: Install packages (EL8)
  when: ansible_distribution_major_version == "8"
  yum:
    name: python36,uwsgi,uwsgi-plugin-python3,uwsgi-logger-file,nginx,git,wget
    state: present
    update_cache: yes
